# Define 'Secret' to store db-credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials # Name of the 'Secret'
data:
  username: devops  # base64 encoded 'Secret' username
  password: Welcome@123 # base64 encoded 'Secret' password
